apiVersion: v1
entries:
  taka-auth:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-07T03:19:48.219556879Z"
    description: A Helm chart for Kubernetes
    digest: 3fe1a6e3e1dbabbbf2a13330c937a31eb25adb9d982501a10a1f78c8a9a912f8
    name: taka-auth
    type: application
    urls:
    - https://takasecure.github.io/repo/charts/taka-auth-1.0.0.tgz
    version: 1.0.0
  taka-backup:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-07T03:19:48.220313636Z"
    description: A Helm chart for Kubernetes
    digest: ec70b465590d7e5b1e3ddc10108104e41ab493f57f6def6e8344ceced5918adc
    name: taka-backup
    type: application
    urls:
    - https://takasecure.github.io/repo/charts/taka-backup-1.0.0.tgz
    version: 1.0.0
  taka-crypto:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-07T03:19:48.221524772Z"
    description: A Helm chart for Kubernetes
    digest: 182096adabf3b48edecb2059e596463203492bec9535668ab186c21a2800738e
    name: taka-crypto
    type: application
    urls:
    - https://takasecure.github.io/repo/charts/taka-crypto-1.0.0.tgz
    version: 1.0.0
  taka-dispatch:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-07T03:19:48.222176613Z"
    description: A Helm chart for Kubernetes
    digest: c5e2627f2485420f4251dd2ef35034ad104c80485dee07969afa9b5d93c3e572
    name: taka-dispatch
    type: application
    urls:
    - https://takasecure.github.io/repo/charts/taka-dispatch-1.0.0.tgz
    version: 1.0.0
  taka-gateway:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-07T03:19:48.222670872Z"
    description: A Helm chart for Kubernetes
    digest: 4997fa89ef5a13aec7014d8a99215eb12af5b228cddd1a763ea4f5f8f61311b6
    name: taka-gateway
    type: application
    urls:
    - https://takasecure.github.io/repo/charts/taka-gateway-1.0.0.tgz
    version: 1.0.0
  taka-masking:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-12-07T03:19:48.223178085Z"
    description: A Helm chart for Kubernetes
    digest: 9e41ae34791318b065fd40209cfe0adaca13888dde05136858d67890226ebfeb
    name: taka-masking
    type: application
    urls:
    - https://takasecure.github.io/repo/charts/taka-masking-1.0.0.tgz
    version: 1.0.0
generated: "2025-12-07T03:19:48.218699716Z"
